### ISSUE TITLE
another problem in update_articles()

### ISSUE THREAD

**Issue by skiane** [snewscms/snews1.80#7]
#2 is now fixed, however, **fetch**() produce the following exception with mysql :

```
/usr/local/php5.6/bin/php  testadmin.php 

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2053 ' in /home/www/snews1.80/snews.php:266
Stack trace:
#0 /home/www/snews1.80/snews.php(266): PDOStatement->fetch()
#1 /home/www/snews1.80/snews.php(454): update_articles()
#2 /home/www/snews1.80/index.php(4): include('/home/w...')
#3 /home/www/snews1.80/testadmin.php(10): include_once('/home/w...')
#4 {main}
```

It should be replaced by ->**execute**()

**Comment by snewscms** [comment]
I think "execute" is for prepared statement.

For me fetchAll() is better solution, can you try it?

I did run tests and works for both databases (mysql and slite)

Don't forget choose correct engine in config.php
engine = "sqlite" for sQLite
engine = "mysql" for mysql

**Comment by skiane** [comment]
I guess config.php is fine because the site is working correctly.

```
[DATABASE]
; database engine (mysql,sqlite)
engine = "mysql"
dsn = "mysql:host=mysql5;dbname=db"
```

Btw, I using mysql version 5.

**Comment by snewscms** [comment]
Yes I think is OK.

Same version mysql.
Can you create an article for future publish or modify in phpadmin (article-set "publish=2" and settings "last_date" ).

```
// ARTICLES - FUTURE POSTING
function update_articles() {
    $last_date = s('last_date');
    $updatetime = !empty($last_date) ? strtotime($last_date) : time();
    $dif_time = time() - $updatetime;
    if ($dif_time > 1200 || empty($last_date)) {
        $now = defined('DBTYPE') && DBTYPE == 'sqlite' ? 
            'datetime('.strtotime("now").')' : 'NOW()';
        $sql1 = "UPDATE "._PRE."articles 
            SET published = 1 
            WHERE published = 2 AND date <= ".$now;
        if ($q1 = db() -> query($sql1)) {
            $q1->fetchAll();
        }
        $date = date('Y-m-d H:i:s');
        $sql2 = "UPDATE "._PRE."settings
            SET value = '$date'
            WHERE name = 'last_date' AND value = '$last_date'";
        if ($q2 = db() -> query($sql2)) {
            $q2->fetchAll();
        }
    }
}
```

**Comment by skiane** [comment]
Does not work with fetchAll either:

```
 Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2053 ' in /home/www/snews1.80/snews.php:269
Stack trace:
#0 /home/www/snews1.80/snews.php(269): PDOStatement-&gt;fetchAll()
#1 /home/www/snews1.80/snews.php(459): update_articles()
#2 /home/www/snews1.80/index.php(4): include('/home/seechac/w...')
#3 {main}
  thrown in <b>/home/www/snews1.80/snews.php</b> on line <b>269</b><br />
```

**Comment by snewscms** [comment]
Update let see if works for you

```
// ARTICLES - FUTURE POSTING
function update_articles() {
    $last_date = s('last_date');
    $updatetime = !empty($last_date) ? strtotime($last_date) : time();
    $dif_time = time() - $updatetime;
    if ($dif_time > 1200 || empty($last_date)) {
        $date = date('Y-m-d H:i:s');
        $now = defined('DBTYPE') && DBTYPE == 'sqlite' ? 'datetime('.strtotime("now").')' : 'NOW()';
        db()->exec("UPDATE "._PRE."articles SET published = 1 WHERE published = 2 AND date <= $now");
        db()->exec("UPDATE "._PRE."settings SET value = '$date' WHERE name = 'last_date' AND value = '$last_date'");
    }
}
```

For me work for fetch, fetchAll and exec

**Comment by snewscms** [comment]
I believe s working.
